const AFFILIATE_LINKS = Object.freeze({
  stay: "https://www.trip.com/hotels/list?city=734&Allianceid=9886696&SID=328568199&trip_sub1=autumnkyoto_en_stay&trip_sub3=D19242778",
  osakaStay: "https://www.trip.com/hotels/osaka-hotels-list-219/?Allianceid=9886696&SID=328568199&trip_sub1=autumnkyoto_en_osaka_stay&trip_sub3=D19248042",
  transport: "https://www.trip.com/trains/tt-common/ttlist?departurecitycode=JP03869&arrivalcitycode=JP00531&Allianceid=9886696&SID=328568199&trip_sub1=autumnkyoto_en_transport&trip_sub3=D19242778",
  experience: "https://www.trip.com/things-to-do/experiences/kyoto/?Allianceid=9886696&SID=328568199&trip_sub1=autumnkyoto_en_experience&trip_sub3=D19242778",
  evening: "https://www.trip.com/things-to-do/detail/106174530/?Allianceid=9886696&SID=328568199&trip_sub1=autumnkyoto_en_evening&trip_sub3=D19242778"
});

const BOOKING_LINKS = {
  day: { transport: AFFILIATE_LINKS.transport, experience: AFFILIATE_LINKS.experience, evening: AFFILIATE_LINKS.evening },
  "1n2d": { stay: AFFILIATE_LINKS.stay, transport: AFFILIATE_LINKS.transport, experience: AFFILIATE_LINKS.experience },
  "2n3d": { stay: AFFILIATE_LINKS.stay, transport: AFFILIATE_LINKS.transport, experience: AFFILIATE_LINKS.experience },
  "3n4d": { stay: AFFILIATE_LINKS.stay, transport: AFFILIATE_LINKS.transport, experience: AFFILIATE_LINKS.experience }
};

const plans = {
  day: { number:"01", label:"DAY TRIP · EAST KYOTO", title:"East Kyoto essentials", description:"A focused day from Osaka linking Kiyomizu-dera, Gion and Eikando. Compare return transport and timed activities first.", route:"Kiyomizu-dera → Gion → Eikando", priority:"Experience → transport → dinner", check:"Last train time", image:"kyoto-temple-gate.png", imageLabel:"HIGASHIYAMA · 08:00", products:[
    {key:"transport",icon:"券",type:"TRANSPORT",title:"Osaka ↔ Kyoto return transport",copy:"Compare individual fares and passes around your departure station and return time.",meta:["Covered routes","Ticket exchange"],price:"Live seller price",cta:"Compare transport"},
    {key:"experience",icon:"茶",type:"TIME-SLOT EXPERIENCE",title:"Gion or Higashiyama tea ceremony",copy:"An easy timed experience to place between Kiyomizu-dera and Gion.",meta:["Cancellation cutoff","Arrive 15 min early"],price:"Check time slots",cta:"Check experiences"},
    {key:"evening",icon:"灯",type:"EVENING OPTION",title:"Autumn illumination or evening tour",copy:"Add it only after checking the finish time and your final train.",meta:["Finish time","Return route"],price:"Check dates and price",cta:"Compare evenings"}
  ]},
  "1n2d": { number:"02", label:"1 NIGHT · EAST + WEST", title:"East and west Kyoto", description:"Pair a Higashiyama evening with an early Arashiyama morning. Hotel location makes the biggest difference.", route:"Higashiyama → Kawaramachi → Arashiyama", priority:"Hotel → experience → transport", check:"Check-in and luggage storage", image:"kyoto-arashiyama.png", imageLabel:"ARASHIYAMA · 06:50", products:[
    {key:"stay",icon:"宿",type:"STAY",title:"One night near Kawaramachi or Gion",copy:"Prioritize an area that works for the first evening and the next morning's western route.",meta:["Free cancellation","Luggage storage"],price:"Compare 1-night total",cta:"Check hotel prices"},
    {key:"transport",icon:"鉄",type:"TRANSPORT",title:"Transport to Arashiyama",copy:"Choose JR, Hankyu or Randen based on your hotel and first stop.",meta:["First train","Pass coverage"],price:"Compare route fares",cta:"Compare transport"},
    {key:"experience",icon:"茶",type:"EXPERIENCE",title:"Tea ceremony or kimono experience",copy:"A classic option for the first afternoon or after lunch on day two.",meta:["Timed entry","Cancellation cutoff"],price:"Check date availability",cta:"Check experiences"}
  ]},
  "2n3d": { number:"03", label:"2 NIGHTS · BALANCED KYOTO", title:"Three-area Kyoto plan", description:"Give Higashiyama, Arashiyama and northern Kyoto one day each. Two nights in one hotel keeps luggage simple.", route:"East Kyoto → Arashiyama → North Kyoto", priority:"Hotel → transport → experience", check:"Multi-night terms and route coverage", image:"kyoto-tea.png", imageLabel:"NISHIJIN · 15:30", products:[
    {key:"stay",icon:"宿",type:"STAY",title:"Two nights in central Kyoto",copy:"Compare the same-room total near Kawaramachi or Kyoto Station.",meta:["Total for 2 nights","Free cancellation"],price:"Compare total stay",cta:"Check hotel prices"},
    {key:"transport",icon:"乗",type:"CITY TRANSPORT",title:"Three-day transport mix",copy:"Compare pay-as-you-go fares with passes for one area per day.",meta:["JR coverage","Bus congestion"],price:"Compare pass and fares",cta:"Compare transport"},
    {key:"experience",icon:"景",type:"DAY EXPERIENCE",title:"North Kyoto gardens or small tour",copy:"For transfer-heavy days, compare a small tour or private vehicle option.",meta:["Meeting point","Entry fees"],price:"Check product terms",cta:"Compare experiences"}
  ]},
  "3n4d": { number:"04", label:"3 NIGHTS · SLOW KYOTO", title:"A deeper Kyoto itinerary", description:"Add Uji or Ohara to three classic Kyoto areas. Secure the three-night stay before day-trip transport and activities.", route:"Higashiyama → Arashiyama → North → Day trip", priority:"Hotel → day-trip transport → experience", check:"Three-night total and operating days", image:"kyoto-arashiyama.png", imageLabel:"UJI / OHARA · DAY 04", products:[
    {key:"stay",icon:"宿",type:"STAY",title:"Three nights in central Kyoto",copy:"Compare the final total after taxes, breakfast and room conditions.",meta:["Final total","Room-change terms"],price:"Compare 3-night total",cta:"Check hotel prices"},
    {key:"transport",icon:"郊",type:"DAY-TRIP TRANSPORT",title:"Transport to Uji or Ohara",copy:"Check JR or Keihan for Uji and bus timetables for Ohara.",meta:["Return journey","Last service"],price:"Check route fares",cta:"Compare transport"},
    {key:"experience",icon:"茶",type:"LOCAL EXPERIENCE",title:"Uji tea or Ohara tour",copy:"Choose a timed experience or guided tour to match the pace of your last day.",meta:["Operating days","Transport included"],price:"Check date options",cta:"Compare experiences"}
  ]}
};

const productImages = {stay:"kyoto-booking-stay.png",transport:"kyoto-booking-train.png",experience:"kyoto-tea.png",evening:"kyoto-booking-night.png"};
const LOCAL_PLACES = Object.freeze({
  kiyomizu:{kicker:"LOCAL DRIVER IWAMA · HIGASHIYAMA",title:"Kiyomizu-dera at 6 a.m.",intro:"See Kyoto's famous hillside temple in the quiet early light before the main crowds arrive.",time:"At or just after opening",route:"Chawanzaka → Kiyomizu-dera → Sannenzaka",tip:"Many shops will still be closed. Enjoy the scenery first, then eat and shop on the way down.",image:"pexels-kiyomizudera-hero.png",source:"https://kyoto.travel/en/travel-inspiration/11-secret-tips-for-enjoying-kyoto-from-a-local-taxi-driver/"},
  east:{kicker:"LOCAL DRIVER IWAMA · EAST KYOTO",title:"Imakumano Kannonji and Unryuin",intro:"A quieter eastern Kyoto pair for autumn color and temple calm away from the busiest circuit.",time:"Morning or late afternoon",route:"Imakumano Kannonji → Sennyuji grounds → Unryuin",tip:"Choose these two and explore slowly instead of packing in several famous temples.",image:"kyoto-temple-gate.png",source:"https://kyoto.travel/en/travel-inspiration/11-secret-tips-for-enjoying-kyoto-from-a-local-taxi-driver/"},
  ohara:{kicker:"KYOTO WRITER ABBY · OHARA",title:"Slow down in Ohara",intro:"A gentle half-day linking Sanzenin's moss and maples with the village walk toward Jakko-in.",time:"Morning departure · half day",route:"Sanzenin → Ohara village → Jakko-in",tip:"The temples sit on opposite sides of the valley, so check your return bus before walking across.",image:"kyoto-booking-stay.png",source:"https://kyoto.travel/en/hidden-gems/ohara-tranquil-getaway-to-the-north-of-kyoto/"},
  takao:{kicker:"KYOTO CITY OFFICIAL · TAKAO",title:"Mountain temples and the Kiyotaki River",intro:"Autumn often arrives earlier in Takao, where old temples meet a clear riverside path.",time:"Earlier in the fall-color season",route:"Saimyoji or Jingoji → Kiyotaki River",tip:"There are many stone steps. Pick two temples rather than all three and wear supportive shoes.",image:"kyoto-arashiyama.png",source:"https://kyoto.travel/en/hidden-gems/riverside-dining-in-takao/"},
  west:{kicker:"LOCAL DRIVER IWAMA · WEST KYOTO",title:"Arashiyama beyond the bamboo grove",intro:"Continue into old Saga-Toriimoto and choose Otagi Nenbutsuji or Rokuoin for a calmer western Kyoto.",time:"Morning, after the bamboo grove",route:"Saga-Toriimoto → Otagi Nenbutsuji or Rokuoin",tip:"The two temples are in different directions, so choose one and pair it with nearby lanes.",image:"kyoto-autumn-hero.png",source:"https://kyoto.travel/en/travel-inspiration/11-secret-tips-for-enjoying-kyoto-from-a-local-taxi-driver/"},
  yamashina:{kicker:"KYOTO CITY OFFICIAL · YAMASHINA",title:"Bishamondo and the Yamashina Canal",intro:"Combine a maple-framed temple with an easy canal walk in Kyoto's eastern gateway district.",time:"Morning or afternoon walk",route:"JR Yamashina → Bishamondo → Canal → Misasagi",tip:"Parts of the canal approach may be unpaved, especially after rain.",image:"kyoto-booking-train.png",source:"https://kyoto.travel/en/destinations/running-course-yamashina/"},
  nishikyo:{kicker:"KYOTO CITY OFFICIAL · RAKUSAI",title:"Mountain color at Yoshiminedera",intro:"A broad hillside temple combining autumn foliage with views across Kyoto.",time:"Morning · half day",route:"Yoshiminedera → optional Oharano",tip:"Set your return bus time before beginning this mountain-side visit.",image:"kyoto-booking-night.png",source:"https://kyoto.travel/en/hidden-gems/rakusai-a-pilgrimage-to-the-green-of-western-kyoto/"}
});

let currentDuration="day"; const completed=new Set(); const tabs=[...document.querySelectorAll(".duration-tab")]; const productList=document.querySelector("#product-list"); const toast=document.querySelector("#booking-toast"); const placeModal=document.querySelector("#place-modal"); const placeModalClose=placeModal.querySelector(".place-modal-close"); let placeModalReturnFocus=null;
function productCard(product){const done=completed.has(`${currentDuration}:${product.key}`);return `<article class="product-card${done?" completed":""}" data-product="${product.key}"><div class="product-thumb" style="background-image:url(&quot;${productImages[product.key]}&quot;)"><span>${product.icon}</span></div><div class="product-copy"><small>${product.type}</small><h4>${product.title}</h4><p>${product.copy}</p><div class="product-meta">${product.meta.map(item=>`<span>${item}</span>`).join("")}</div></div><div class="product-action"><span>${product.price}</span><button class="booking-cta" type="button" data-key="${product.key}">${done?"Check again":product.cta}</button></div></article>`}
function updateProgress(){const done=plans[currentDuration].products.filter(p=>completed.has(`${currentDuration}:${p.key}`)).length;document.querySelector("#checked-count").textContent=String(done);document.querySelector("#progress-bar").style.width=`${done/3*100}%`}
function showToast(message){toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),2800)}
function renderPlan(duration){currentDuration=duration;const p=plans[duration];for(const [id,key] of [["plan-number","number"],["plan-label","label"],["plan-title","title"],["plan-description","description"],["plan-route","route"],["plan-priority","priority"],["plan-check","check"],["plan-image-label","imageLabel"]])document.querySelector(`#${id}`).textContent=p[key];document.querySelector("#plan-image").style.backgroundImage=`url("${p.image}")`;productList.innerHTML=p.products.map(productCard).join("");tabs.forEach(tab=>{const active=tab.dataset.duration===duration;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active));tab.querySelector("b").textContent=active?"Selected":"Select"});const saved=localStorage.getItem("autumnKyotoSavedPlanEn")===duration;const button=document.querySelector("#save-plan");button.classList.toggle("saved",saved);button.innerHTML=saved?"<span>♥</span> Saved plan":"<span>♡</span> Save this plan";document.querySelectorAll('a[href^="kyoto-autumn-guide-en.html"]').forEach(link=>{link.href=`kyoto-autumn-guide-en.html?plan=${encodeURIComponent(duration)}`});const url=new URL(window.location.href);url.searchParams.set("plan",duration);url.hash="book";window.history.replaceState({},"",`${url.pathname}${url.search}${url.hash}`);updateProgress()}
tabs.forEach((tab,index)=>{tab.addEventListener("click",()=>renderPlan(tab.dataset.duration));tab.addEventListener("keydown",event=>{if(!["ArrowLeft","ArrowRight"].includes(event.key))return;event.preventDefault();const next=event.key==="ArrowRight"?(index+1)%tabs.length:(index-1+tabs.length)%tabs.length;tabs[next].focus();renderPlan(tabs[next].dataset.duration)})});
productList.addEventListener("click",event=>{const button=event.target.closest(".booking-cta");if(!button)return;const key=button.dataset.key;completed.add(`${currentDuration}:${key}`);window.open(BOOKING_LINKS[currentDuration][key],"_blank","noopener,noreferrer");showToast("The seller opened in a new tab. Confirm the final booking and terms there.");renderPlan(currentDuration)});
document.querySelector("#save-plan").addEventListener("click",()=>{const saved=localStorage.getItem("autumnKyotoSavedPlanEn")===currentDuration;if(saved)localStorage.removeItem("autumnKyotoSavedPlanEn");else localStorage.setItem("autumnKyotoSavedPlanEn",currentDuration);renderPlan(currentDuration)});
const menuButton=document.querySelector(".menu-toggle"),navigation=document.querySelector("#site-nav");menuButton.addEventListener("click",()=>{const open=navigation.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});navigation.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{navigation.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}));
function openPlaceModal(key,trigger){const p=LOCAL_PLACES[key];if(!p)return;for(const [id,field] of [["place-modal-kicker","kicker"],["place-modal-title","title"],["place-modal-intro","intro"],["place-modal-time","time"],["place-modal-route","route"],["place-modal-tip","tip"]])document.querySelector(`#${id}`).textContent=p[field];const image=document.querySelector("#place-modal-image");image.style.backgroundImage=`url("${p.image}")`;image.setAttribute("aria-label",`${p.title} atmosphere image`);document.querySelector("#place-modal-link").href=p.source;placeModalReturnFocus=trigger;placeModal.hidden=false;document.body.classList.add("modal-open");placeModalClose.focus()}
function closePlaceModal(){if(placeModal.hidden)return;placeModal.hidden=true;document.body.classList.remove("modal-open");if(placeModalReturnFocus)placeModalReturnFocus.focus()}
document.querySelector(".local-card-track").addEventListener("click",event=>{const card=event.target.closest(".local-card");if(card)openPlaceModal(card.dataset.place,card)});placeModal.querySelectorAll("[data-modal-close]").forEach(c=>c.addEventListener("click",closePlaceModal));document.addEventListener("keydown",event=>{if(!placeModal.hidden&&event.key==="Escape")closePlaceModal()});
document.querySelector("#osaka-stay-link").href=AFFILIATE_LINKS.osakaStay;document.querySelector("#year").textContent=new Date().getFullYear();const requestedPlan=new URLSearchParams(window.location.search).get("plan");renderPlan(Object.hasOwn(plans,requestedPlan)?requestedPlan:"day");
